package com.github.andiim.orchidscan.app.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFAF0095)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7EE)
val md_theme_light_onPrimaryContainer = Color(0xFF3A0030)
val md_theme_light_secondary = Color(0xFF87458A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD6FB)
val md_theme_light_onSecondaryContainer = Color(0xFF36003D)
val md_theme_light_tertiary = Color(0xFF456812)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5F08B)
val md_theme_light_onTertiaryContainer = Color(0xFF102000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF9FFE8)
val md_theme_light_onBackground = Color(0xFF112000)
val md_theme_light_surface = Color(0xFFF9FFE8)
val md_theme_light_onSurface = Color(0xFF112000)
val md_theme_light_surfaceVariant = Color(0xFFEFDEE6)
val md_theme_light_onSurfaceVariant = Color(0xFF4F444A)
val md_theme_light_outline = Color(0xFF81737A)
val md_theme_light_inverseOnSurface = Color(0xFFD4FF97)
val md_theme_light_inverseSurface = Color(0xFF203600)
val md_theme_light_inversePrimary = Color(0xFFFFADE4)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFAF0095)
val md_theme_light_outlineVariant = Color(0xFFD2C2CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFADE4)
val md_theme_dark_onPrimary = Color(0xFF5F0050)
val md_theme_dark_primaryContainer = Color(0xFF860071)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7EE)
val md_theme_dark_secondary = Color(0xFFFAACF9)
val md_theme_dark_onSecondary = Color(0xFF521458)
val md_theme_dark_secondaryContainer = Color(0xFF6C2D70)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD6FB)
val md_theme_dark_tertiary = Color(0xFFAAD472)
val md_theme_dark_onTertiary = Color(0xFF203700)
val md_theme_dark_tertiaryContainer = Color(0xFF304F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5F08B)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF112000)
val md_theme_dark_onBackground = Color(0xFFC6F08A)
val md_theme_dark_surface = Color(0xFF112000)
val md_theme_dark_onSurface = Color(0xFFC6F08A)
val md_theme_dark_surfaceVariant = Color(0xFF4F444A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD2C2CA)
val md_theme_dark_outline = Color(0xFF9B8D94)
val md_theme_dark_inverseOnSurface = Color(0xFF112000)
val md_theme_dark_inverseSurface = Color(0xFFC6F08A)
val md_theme_dark_inversePrimary = Color(0xFFAF0095)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFADE4)
val md_theme_dark_outlineVariant = Color(0xFF4F444A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFDF06BE)
