[versions]
# SDK VERSION
compile_sdk_version = "33"
gson = "2.10.1"
integrity = "1.2.0"
kotlinxDatetime = "0.4.1"
min_sdk_version = "27"
objectDetection = "17.0.0"
target_sdk_version = "33"
compose_compilerextension = "1.5.0"
kotlin = "1.9.0"

# DEPENDENCIES
agp = "8.1.1"
activity = "1.7.2"
androidDesugarJdkLibs = "2.0.3"
androidx_activity_compose = "1.7.2"
androidx_test = "1.5.2"
androidx_test_rules = "1.5.0"
androidx_test_ext = "1.1.5"
profileInstaller = "1.3.1"
appcompat = "1.6.1"
camerax_version = "1.2.3"
coroutines = "1.7.3"
coil = "2.4.0"
compose = "2023.06.01"
constraint_layout = "2.1.4"
core_ktx = "1.10.1"
detekt = "1.23.0"
dokka = "1.8.20"
espresso_core = "3.5.1"
firebase = "32.2.2"
hilt = "2.48"
junit = "4.13.2"
jacoco = "0.8.7"
ktlint = "0.45.2"
ktlint_gradle = "10.2.1"
lifecycle = "2.6.1"
material = "1.9.0"
navigation = "2.6.0"
benmanesversion = "0.47.0"
timber = "5.0.1"
truth = "1.1.5"
org-jetbrains-kotlin-android = "1.8.0"
constraintlayout = "2.1.4"
retrofit = "2.9.0"
kotlinx-serialization = "1.0.0"
kotlinx-serialization-json = "1.5.1"
secrets = "2.0.1"
okhttp = "4.10.0"
window = "1.0.0"
ksp = "1.9.0-1.0.11"

[libraries]
androidx-window = { module = "androidx.window:window-java", version.ref = "window" }
androidx-window-extension = { module = "androidx.window.extensions.core:core", version.ref = "window" }
junit = { module = "junit:junit", version.ref = "junit" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version = "0.30.1" }
accompanist_permission = { module = "com.google.accompanist:accompanist-permissions", version = "0.30.1" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx" }
androidx_core_testing = { module = "androidx.arch.core:core-testing", version = "2.2.0" }
androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx_test_rules" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx_test" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "androidx_test_ext" }
androidx_test_ext_junit_ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx_test_ext" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx_mockito = { module = "org.mockito:mockito-core", version = "4.8.1" }
androidx_mockito_android = { module = "org.mockito:mockito-android", version = "4.8.1" }
androidx_mockito_inline = { module = "org.mockito:mockito-inline", version = "4.8.1" }
androidx_mockito_dexmaker = { module = "com.linkedin.dexmaker:dexmaker-mockito-inline", version = "2.28.1" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileInstaller" }
autofactory = {group="com.google.auto.factory", name = "auto-factory", version = "1.0.1"}
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
dagger_hilt_navigation_compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
dagger_hilt_testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
camera = { module = "androidx.camera:camera-camera2", version.ref = "camerax_version" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax_version" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax_version" }
camera-video = { module = "androidx.camera:camera-video", version.ref = "camerax_version" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax_version" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camerax_version" }
coil = { module = "io.coil-kt:coil", version = "2.4.0" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-material = { group = "androidx.compose.material3", name = "material3", version = "1.2.0-alpha02" }
compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-runtimeLivedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version = "1.5.0" }
compose-ui-viewBinding = { module = "androidx.compose.ui:ui-viewbinding" }
detekt_formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso_core" }
espresso_intent = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso_core" }
espresso_idlingResource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso_core" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-appdistribution-plugin = { group = "com.google.firebase", name = "firebase-appdistribution-gradle", version = "4.0.0" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-config = { group = "com.google.firebase", name = "firebase-config-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-crashlytics-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.9.8" }
firebase-perf-plugin = { group = "com.google.firebase", name = "perf-plugin", version = "1.4.2" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-storage = { module = "com.google.firebase:firebase-storage-ktx" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-coroutines-test-turbine = { module = "app.cash.turbine:turbine", version = "1.0.0" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version = "2.6.0" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version = "2.6.0" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation" }

agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dhp = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
ksp-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

dokka_gradle_plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka_core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka" }
paging-common = { module = "androidx.paging:paging-common-ktx", version = "3.2.0" }
paging-compose = { module = "androidx.paging:paging-compose", version = "3.2.0" }
paging-testing = { module = "androidx.paging:paging-testing", version = "3.2.0" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version = "20.7.0" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
metrics-performance = { group = "androidx.metrics", name = "metrics-performance", version = "1.0.0-alpha04" }

[bundles]
retrofit = ["retrofit-core", "retrofit-kotlin-serialization", "kotlinx-serialization-json", "okhttp-logging"]
camera = ["camera", "camera-core", "camera-lifecycle", "camera-extensions", "camera-video", "camera-view"]
compose = ["coil-compose", "compose-activity", "compose-material", "compose-materialIcons", "compose-runtimeLivedata", "compose-ui", "compose-ui-graphics", "compose-ui-tooling-preview", "navigation-compose", "compose-ui-viewBinding", "androidx-lifecycle-runtimeCompose"]
compose-debug = ["compose-ui-tooling", "compose-ui-test-manifest"]
navigation = ["navigation-ui", "navigation-fragment-ktx"]
firebase = ["firebase-auth", "firebase-config", "firebase-crashlytics", "firebase-firestore", "firebase-analytics", "firebase-perf", "firebase-messaging", "firebase-storage"]
lifecycle = ["lifecycle-livedata", "lifecycle-runtime", "lifecycle-viewmodel-compose"]
paging = ["paging-common", "paging-compose"]

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint.gradle" }
versions = { id = "com.github.ben-manes.versions", version.ref = "benmanesversion" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }